image: python:3.6-stretch


before_script:
    - pip install -r requirements.txt

stages:
    - test

test:
  script:
    - python -m ./test.py

## production:
##    stage: deploy
##    script:
##        - sudo apt-get update -qy
##        - sudo apt-get install -y 
