image: python:3.6-stretch


before_script:
    - pip install -r requirements.txt

stages:
    - linting
    - test

flake8:
    stage: linting
    script:
        - flake8 --ignore=E1,E23,W503

test:
  script:
    - python -m unittest discover tests

## production:
##    stage: deploy
##    script:
##        - sudo apt-get update -qy
##        - sudo apt-get install -y 
