stages:
    - init
    - tests
    - deploy

init:
    stage: init
    script:
        - export DATABASE_URL=$TINY_DATABASE_URI
        - apt-get update -qy
        - apt-get install -y python3-dev python3-pip
        - pip3 install -r requirements.txt

run_tests:
    stage: tests
    script:
        - export DATABASE_URL=$TINY_DATABASE_URI
        - export SECRET_KEY=12345678
        - apt-get update -qy
        - apt-get install -y python3-dev python3-pip
        - pip3 install -r requirements.txt
        - python3 tests_utils.py

deploy_staging:
    stage: deploy
    script:
        - export DATABASE_URL=$TINY_DATABASE_URI
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=move02-flask-test --api-key=$HEROKU_SECRET_KEY
        - echo "Deployed to Staging Server https://move02-flask-test.herokuapp.com"
        - flask db upgrade
        - python app/command/db_init.py
    environment:
        name: staging
        url: https://move02-flask-test.herokuapp.com/
    only:
        - master


# staging:
#     stage: deploy
#     script:
#         - apt-get update -qy
#         - apt-get install -y ruby-dev
#         - gem install dpl
#         - dpl --provider=heroku --app=move02-flask-test --api-key=$HEROKU_SECRET_KEY
    # only:
    #     - master
