"""empty message

Revision ID: 1177ee2a8a3a
Revises: d90e447df483
Create Date: 2020-07-31 16:22:55.239797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1177ee2a8a3a'
down_revision = 'd90e447df483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_T_COMCODE_M01_GROUP_CODE', table_name='T_COMCODE_M01')
    op.drop_index('ix_T_COMCODE_M01_ID', table_name='T_COMCODE_M01')
    op.drop_table('T_COMCODE_M01')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_COMCODE_M01',
    sa.Column('GROUP_CODE', sa.VARCHAR(length=30), nullable=False),
    sa.Column('ID', sa.VARCHAR(length=30), nullable=False),
    sa.Column('CODE_VALUE', sa.VARCHAR(length=30), nullable=False),
    sa.Column('REGIST_DATE', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('CODE_DC', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('USE_AT', sa.BOOLEAN(), nullable=False),
    sa.Column('RM_1', sa.VARCHAR(length=50), nullable=True),
    sa.Column('RM_2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('RM_3', sa.VARCHAR(length=50), nullable=True),
    sa.CheckConstraint('"USE_AT" IN (0, 1)'),
    sa.PrimaryKeyConstraint('GROUP_CODE', 'ID')
    )
    op.create_index('ix_T_COMCODE_M01_ID', 'T_COMCODE_M01', ['ID'], unique=1)
    op.create_index('ix_T_COMCODE_M01_GROUP_CODE', 'T_COMCODE_M01', ['GROUP_CODE'], unique=1)
    # ### end Alembic commands ###
