"""init2

Revision ID: 3229878d149a
Revises: 
Create Date: 2020-07-20 17:26:18.712865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3229878d149a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('incharge_region', sa.String(length=140), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_index(op.f('ix_note_email'), 'note', ['email'], unique=True)
    op.create_index(op.f('ix_note_username'), 'note', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_username'), table_name='note')
    op.drop_index(op.f('ix_note_email'), table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###
