"""empty message

Revision ID: 4459fb95cf12
Revises: 
Create Date: 2020-08-03 10:07:10.889359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4459fb95cf12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_ADMIN_INFO_M01',
    sa.Column('SN', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID', sa.String(length=30), nullable=False),
    sa.Column('NM', sa.String(length=100), nullable=False),
    sa.Column('PASSWORD', sa.String(length=255), nullable=False),
    sa.Column('TELNO', sa.String(length=15), nullable=True),
    sa.Column('CONFM_AT', sa.Boolean(), nullable=False),
    sa.Column('CONFM_ID', sa.String(length=30), nullable=True),
    sa.Column('CONFM_DATE', sa.DateTime(), nullable=True),
    sa.Column('REGIST_DATE', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('UPDT_ID', sa.String(length=30), nullable=True),
    sa.Column('UPDT_DATE', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('DELETE_AT', sa.Boolean(), nullable=False),
    sa.Column('DELETE_ID', sa.String(length=30), nullable=True),
    sa.Column('DELETE_DATE', sa.DateTime(), nullable=True),
    sa.Column('LAST_LOGIN', sa.DateTime(), nullable=True),
    sa.Column('AUTHOR', sa.String(length=20), nullable=True),
    sa.Column('JURANG', sa.String(length=20), nullable=True),
    sa.Column('EMAIL', sa.String(length=50), nullable=False),
    sa.Column('INSTT_NM', sa.String(length=100), nullable=True),
    sa.Column('DEPT_NM', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('SN'),
    mysql_collate='utf8_general_ci'
    )
    op.create_index(op.f('ix_T_ADMIN_INFO_M01_EMAIL'), 'T_ADMIN_INFO_M01', ['EMAIL'], unique=True)
    op.create_index(op.f('ix_T_ADMIN_INFO_M01_ID'), 'T_ADMIN_INFO_M01', ['ID'], unique=True)
    op.create_index(op.f('ix_T_ADMIN_INFO_M01_NM'), 'T_ADMIN_INFO_M01', ['NM'], unique=False)
    op.create_table('T_COMCODE_M01',
    sa.Column('GROUP_CODE', sa.String(length=30), nullable=False),
    sa.Column('CODE', sa.String(length=30), nullable=False),
    sa.Column('CODE_VALUE', sa.String(length=30), nullable=False),
    sa.Column('REGIST_DATE', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('CODE_DC', sa.String(length=1000), nullable=True),
    sa.Column('USE_AT', sa.Boolean(), nullable=False),
    sa.Column('RM_1', sa.String(length=50), nullable=True),
    sa.Column('RM_2', sa.String(length=50), nullable=True),
    sa.Column('RM_3', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('GROUP_CODE', 'CODE'),
    mysql_collate='utf8_general_ci'
    )
    op.create_index(op.f('ix_T_COMCODE_M01_CODE'), 'T_COMCODE_M01', ['CODE'], unique=True)
    op.create_index(op.f('ix_T_COMCODE_M01_GROUP_CODE'), 'T_COMCODE_M01', ['GROUP_CODE'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_T_COMCODE_M01_GROUP_CODE'), table_name='T_COMCODE_M01')
    op.drop_index(op.f('ix_T_COMCODE_M01_CODE'), table_name='T_COMCODE_M01')
    op.drop_table('T_COMCODE_M01')
    op.drop_index(op.f('ix_T_ADMIN_INFO_M01_NM'), table_name='T_ADMIN_INFO_M01')
    op.drop_index(op.f('ix_T_ADMIN_INFO_M01_ID'), table_name='T_ADMIN_INFO_M01')
    op.drop_index(op.f('ix_T_ADMIN_INFO_M01_EMAIL'), table_name='T_ADMIN_INFO_M01')
    op.drop_table('T_ADMIN_INFO_M01')
    # ### end Alembic commands ###
