"""empty message

Revision ID: 95ff19da85a2
Revises: dc4b5ab9d21f
Create Date: 2020-08-24 17:13:53.239226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95ff19da85a2'
down_revision = 'dc4b5ab9d21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_t_dummy_A', table_name='t_dummy')
    op.drop_table('t_dummy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_dummy',
    sa.Column('A', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('A'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_t_dummy_A', 't_dummy', ['A'], unique=False)
    # ### end Alembic commands ###
