"""table name changes

Revision ID: b543f257aa0c
Revises: 3229878d149a
Create Date: 2020-07-20 17:27:34.963569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b543f257aa0c'
down_revision = '3229878d149a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mytable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('incharge_region', sa.String(length=140), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_index(op.f('ix_mytable_email'), 'mytable', ['email'], unique=True)
    op.create_index(op.f('ix_mytable_username'), 'mytable', ['username'], unique=True)
    op.drop_index('ix_note_email', table_name='note')
    op.drop_index('ix_note_username', table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('incharge_region', mysql.VARCHAR(length=140), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_note_username', 'note', ['username'], unique=True)
    op.create_index('ix_note_email', 'note', ['email'], unique=True)
    op.drop_index(op.f('ix_mytable_username'), table_name='mytable')
    op.drop_index(op.f('ix_mytable_email'), table_name='mytable')
    op.drop_table('mytable')
    # ### end Alembic commands ###
