"""empty message

Revision ID: bfb2b5fa8e7f
Revises: 1f80fdc5e2e1
Create Date: 2020-08-24 17:09:44.376542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfb2b5fa8e7f'
down_revision = '1f80fdc5e2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_comcode_m01',
    sa.Column('GROUP_CODE', sa.String(length=30), nullable=False),
    sa.Column('CODE', sa.String(length=30), nullable=False),
    sa.Column('CODE_VALUE', sa.String(length=30), nullable=False),
    sa.Column('REGIST_DATE', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('CODE_DC', sa.String(length=1000), nullable=True),
    sa.Column('USE_AT', sa.Boolean(), nullable=False),
    sa.Column('RM_1', sa.String(length=50), nullable=True),
    sa.Column('RM_2', sa.String(length=50), nullable=True),
    sa.Column('RM_3', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('GROUP_CODE', 'CODE'),
    mysql_collate='utf8_general_ci'
    )
    op.create_index(op.f('ix_t_comcode_m01_CODE'), 't_comcode_m01', ['CODE'], unique=True)
    op.create_index(op.f('ix_t_comcode_m01_GROUP_CODE'), 't_comcode_m01', ['GROUP_CODE'], unique=False)
    op.drop_index('ix_t_comcode_01_CODE', table_name='t_comcode_01')
    op.drop_index('ix_t_comcode_01_GROUP_CODE', table_name='t_comcode_01')
    op.drop_table('t_comcode_01')
    op.drop_index('FK_T_USER_LOCATION_D01_PLACE_ID_T_PLACE_INFO_M01_PLACE_ID', table_name='t_user_location_d01')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('FK_T_USER_LOCATION_D01_PLACE_ID_T_PLACE_INFO_M01_PLACE_ID', 't_user_location_d01', ['PLACE_ID'], unique=False)
    op.create_table('t_comcode_01',
    sa.Column('GROUP_CODE', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('CODE', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('CODE_VALUE', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('REGIST_DATE', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('CODE_DC', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('USE_AT', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('RM_1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('RM_2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('RM_3', mysql.VARCHAR(length=50), nullable=True),
    sa.CheckConstraint('`USE_AT` in (0,1)', name='CONSTRAINT_1'),
    sa.PrimaryKeyConstraint('GROUP_CODE', 'CODE'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_t_comcode_01_GROUP_CODE', 't_comcode_01', ['GROUP_CODE'], unique=False)
    op.create_index('ix_t_comcode_01_CODE', 't_comcode_01', ['CODE'], unique=True)
    op.drop_index(op.f('ix_t_comcode_m01_GROUP_CODE'), table_name='t_comcode_m01')
    op.drop_index(op.f('ix_t_comcode_m01_CODE'), table_name='t_comcode_m01')
    op.drop_table('t_comcode_m01')
    # ### end Alembic commands ###
